### ISSUE TITLE
Shift-Y Does Not Yank Full Line

### ISSUE THREAD

**Issue by xcthulhu** [LightTable/Vim#28]
`shift-y` is a synonym for `yy` in vim... and `yy` is implemented correctly, so this should be straightforward to fix...

**Comment by xcthulhu** [comment]
Hi LightTable/Vim,
A message from Matthew Wampler-Doty was left on IQ Elite for you. 
Click here a.iqelite.com/j/0JmRlo/yl7/?hg=fL8o3NduV5 to read your message 


The IQ Elite Team



---------------------------------------------------------------------------
This message was meant for reply@reply.github.com. If you do not want to continue receiving such mails from IQ Elite, please click on this link: a.iqelite.com/common/unsubscribe/?code=8f5a0f7e&email=reply@reply.github.com&hg=fL8o3NduV5
IQ Elite is a service with main office: C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelona, Spain.
---------------------------------------------------------------------------

**Comment by mbylstra** [comment]
I'm on Light Table 0.8.0-alpha Linux with the plugin Vim 0.2.0 by kodowa, but I can't see a `Vim: map vim keys` behaviour when I search in the commands panel (ctrl-space). Is there another way to map `Y` to `yy` from within Light Table?

**Comment by kenny-evitt** [comment]
@mbylstra You should see the `Vim: map vim keys` behavior when you open a *.behaviors* file in LT. Try opening your *user.behaviors* file and see if you can add the mapping. Also check out [the behaviors file for this plugin](https://github.com/LightTable/Vim/blob/master/vim.behaviors).

**Comment by mbylstra** [comment]
great, thanks for you help!
