### ISSUE TITLE
Select inside not working

### ISSUE THREAD

**Issue by meleyal** [LightTable/Vim#42]
It seems like select inside e.g. `vi"` is not working.

It works in the CodeMirror vim demo:
http://codemirror.net/demo/vim.html

**Comment by nobae** [comment]
Upgrade "vim.js, codemirror.js, codemirror.css" files with the following
https://github.com/codemirror/CodeMirror/archive/5.1.0.zip

to

[LT path]/core/node_modules/codemirror/codemirror.js
[LT path]/core/css/codemirror.css
~/.config/LightTable/plugins/Vim/vim.js

**Comment by yashaka** [comment]
@nobae, did it work for you? for me it broke the "editing" completely...
