### ISSUE TITLE
Cursor only moves once with hjkl hold; doesn't repeat.

### ISSUE THREAD

**Issue by RatanRSur** [LightTable/Vim#49]
OS X Yosemite
Light Table version
0.7.2
Binary version
0.8.4

I was using the exact same setup on Ubuntu previously and this issue wasn't there.

**Comment by cldwalker** [comment]
This has come up before in #8 and #43. See this [faq question](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-auto-repeat-keys-on-osx) for an answer. Cheers
