### ISSUE TITLE
Copy/paste pastes the clipboard together with commands given

### ISSUE THREAD

**Issue by sambarluc** [LightTable/Vim#60]
Hi, I noticed a funny bug in the vim plugin, which I experience only on one of the two (Linux) machines where I use lighttable.
Basically, if I copy something, say a line using `yy`, then I move somewhere, or use other commands, when I paste I get the content of the clipboard and, below, all the letter commands I have given.
So, say that I copied `Hallo`, then moved around using say `jjjlll` when I paste I will get:

    Hallo
    jjjlll

Anyone has seen this before?

**Comment by kenny-evitt** [comment]
@sambarluc I couldn't reproduce this running a build of the latest source version on an Ubuntu 14.04 box with the latest version of the this plugin.

Would you comment with more details about your two Linux boxes, i.e. the Linux distro and version, the version of Light Table, the LT plugins (and versions) installed, and anything else that might be pertinent.

**Comment by sambarluc** [comment]
The machine where it works fine is a Ubuntu 14.04 (kernel 3.13.0-62) with Light Table 0.7.2, binary version 0.8.6, vim plugin 0.1.0 installed from the plugin manager.
The bug shows up on a machine with Linux Mint 17.1 (kernel 3.13.0-37) with the same version of Light Table and plugin.

**Comment by kenny-evitt** [comment]
@sambarluc Try to reproduce this with [the CodeMirror Vim demo](https://codemirror.net/demo/vim.html) – that's what this plugin uses.

**Comment by sambarluc** [comment]
@kenny-evitt  I tried, and tried also to understand what generated the bug on my machine after some reboots, but I actually failed, it seems just random. I would suggest to close the bug, I can always write again if I have new information.
