### ISSUE TITLE
Keybindings not active automatically after installing 0.2.0 on Windows for recent source build

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/Vim#61]
I just installed (not upgraded to) 0.2.0 on a Windows box running a recent source build of Light Table.

No keybindings seem to be active for any files opened after installing the plugin. Keybindings were active after closing and re-opening Light Table.

**Comment by kenny-evitt** [comment]
@cldwalker Is this worth fixing?

**Comment by cldwalker** [comment]
This is part of a bigger issue that afflicts any plugins. After installing a plugin, a `App: Reload behaviors` command invocation is needed for plugin to take effect. I've opened LightTable/LightTable#1970 to track this
